version: "3.9"
services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "23000:3000"
    environment:
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "3306"
      MB_DB_TYPE: "mysql"
      MB_DB_HOST: "db"
    env_file:
      - ".env"
  db:
    image: "mariadb:11.1"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "metabase"
    env_file:
      - ".env"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "23306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30
volumes:
  db-store:

